---
title: "CA_HAB_Bulletin"
author: "Megan Hepner"
date: "7/19/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cowplot) #get_legend 
library(dygraphs) #dygraphs 
library(ggplot2) #ggplot
library(tidyverse)
library(vegan) #spec, diversity
library(htmlwidgets)
library(xts)
library(lubridate) 
library(zoo) #as.yearmon
library(shiny)

#Conflicts: 
#dplyr::filter()   masks stats::filter()
#cowplot::ggsave() masks ggplot2::ggsave()
#dplyr::lag()      masks stats::lag()

select = dplyr::select #override MASS::select 
group_by =  dplyr::group_by #override plotly::group_by
summarise = dplyr::summarise #override plotly::summarise
```

## Marine Mammal Stranding Data

```{r Marine Mammal Strandings}

marine_mammal = read_csv('TMMC_data.csv')

marine_mammal_test = marine_mammal %>%
  select(Age_Class, Sex, Common_Name, Strand_Date, Stranding_City, Stranding_County,Stranding_Locality,Latitude, Longitude, Disposition) %>%
  mutate(Strand_Date = as.Date(Strand_Date, format ="%m/%d/%Y")) %>%
  mutate(Year = format(as.Date(Strand_Date, format="%m/%d/%Y"), "%Y")) %>% 
  mutate(Year_Month = format(as.Date(Strand_Date), "%Y-%m")) %>% 
  group_by(Year_Month) %>% #Age_Class, 
  summarize(Counts = length(Year_Month))

marine_mammal_test_date = marine_mammal %>%
  select(Age_Class, Sex, Common_Name, Strand_Date, Stranding_City, Stranding_County,Stranding_Locality,Latitude, Longitude, Disposition) %>%
  na.omit() %>%
  mutate(Strand_Date = as.Date(Strand_Date, format ="%m/%d/%Y")) %>%
  mutate(Year = format(as.Date(Strand_Date, format="%m/%d/%Y"), "%Y")) %>% 
  mutate(Year_Month = format(as.Date(Strand_Date), "%Y-%m")) %>% 
  group_by(Strand_Date, Age_Class) %>% #Age_Class, 
  summarize(Counts = length(Strand_Date))

marine_mammal_year = marine_mammal %>%
  select(Age_Class, Sex, Common_Name, Strand_Date, Stranding_City, Stranding_County,Stranding_Locality,Latitude, Longitude, Disposition) %>%
  na.omit() %>%
  mutate(Strand_Date = as.Date(Strand_Date, format ="%m/%d/%Y")) %>%
  mutate(Year = format(as.Date(Strand_Date, format="%m/%d/%Y"), "%Y")) %>% 
  mutate(Year_Month = format(as.Date(Strand_Date), "%Y-%m")) %>% 
  group_by(Year) %>% #Age_Class, 
  summarize(Counts = length(Year))

marine_mammal_year_ageclass = marine_mammal %>%
  select(Age_Class, Sex, Common_Name, Strand_Date, Stranding_City, Stranding_County,Stranding_Locality,Latitude, Longitude, Disposition) %>%
  na.omit() %>%
  mutate(Strand_Date = as.Date(Strand_Date, format ="%m/%d/%Y")) %>%
  mutate(Year = format(as.Date(Strand_Date, format="%m/%d/%Y"), "%Y")) %>% 
  mutate(Year_Month = format(as.Date(Strand_Date), "%Y-%m")) %>% 
  group_by(Year, Age_Class) %>% #, 
  summarize(Counts = length(Year))

```

## Plots

```{r pressure, echo=FALSE}

mms_year_month = ggplot(marine_mammal_test, aes(Year_Month, y=Counts)) +
  geom_point(size=2.5) +
  geom_line() +
  labs(x="Time", y= "Sea Lion Strandings")

mms_year = ggplot(marine_mammal_year_ageclass, aes(x=Year, y=Counts, color=Age_Class)) +
  geom_point(size=2.5) +
  geom_line(aes(group=Age_Class), lwd=1.5) +
  labs(x="Year", y= "Sea Lion Strandings") 

mms_year = ggplot(marine_mammal_year, aes(x=as.numeric(Year))) +
  geom_line(aes(y=Counts))+
  labs(x="Year", y= "Sea Lion Strandings")+
  scale_x_continuous(limits = c(1990, 2018), breaks = c(1990, 1992, 1994, 1996, 1998,2000,2002,2004,2006,2008,2010,2012,2014,2016,2018)) 

```

```{r dygraph}

marine_mammal = read_csv('TMMC_data.csv')

# dygraph_test = marine_mammal %>%
#   select(Age_Class, Sex, Common_Name, Strand_Date, Stranding_City, Stranding_County,Stranding_Locality,Latitude, Longitude, Disposition) %>%
#   na.omit() %>%
#   mutate(Strand_Date = as.Date(Strand_Date, format ="%Y/%d/%m")) %>%
#   mutate(Year_Month = format(as.Date(Strand_Date), "%Y-%m")) %>% 
#   group_by(Year_Month) %>% 
#   summarize(Counts = length(Year_Month))

dygraph_test = marine_mammal %>%
  select(Age_Class, Sex, Common_Name, Strand_Date, Stranding_City, Stranding_County,Stranding_Locality,Latitude, Longitude, Disposition) %>%
  na.omit() %>%
  mutate(Strand_Date = as.Date(Strand_Date, format ="%m/%d/%Y")) %>%
  mutate(Year = format(as.Date(Strand_Date, format="%m/%d/%Y"), "%Y")) %>% 
  mutate(Year_Month = format(as.Date(Strand_Date), "%Y-%m")) %>% 
  group_by(Year_Month) %>% #Age_Class, 
  summarize(Counts = length(Year_Month))

dygraph_test$Year_Month = as.yearmon(dygraph_test$Year_Month, "%Y-%m")
don2 = xts(x=dygraph_test$Counts, order.by = dygraph_test$Year_Month)

#dygraph_test$Strand_Date = ymd(dygraph_test$Strand_Date) 
#don = xts(x=dygraph_test$Counts, order.by = dygraph_test$Strand_Date)

dygraph(don2, main = "Sea Lion Strandings", xlab = "", ylab= "Sea Lion Strandings") %>%
  dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.4, drawGrid = T, drawPoints = T) %>% #colors="#D8AE5A"
  dyRangeSelector() %>%
  dyAxis("x", valueRange = c(1990, 2018))
  #dyCrosshair(direction = "vertical") %>%
  #dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  #dyRoller(rollPeriod = 1)


```
